name: Build WASM

on:
  workflow_dispatch

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Master
        uses: actions/checkout@v4
        with:
          path: main

      - name: Checkout Save Github Pages
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.CERT_REPO_TOKEN }}
          path: main/gh-pages

      - name: Install Dependencies
        run: |
          sudo apt-get update && \
          sudo apt-get install -y --no-install-recommends \
          autoconf \
          autoconf-archive \
          automake \
          build-essential \
          ca-certificates \
          clang \
          cmake \
          curl \
          curl \
          git \
          libegl1-mesa-dev \
          libibus-1.0-dev \
          libltdl-dev \
          libssl-dev \
          libtool \
          libwayland-dev \
          libx11-dev \
          libxext-dev \
          libxft-dev \
          libxkbcommon-dev \
          lld \
          ninja-build \
          pkg-config \
          python3 \
          python3-jinja2 \
          tar \
          unzip \
          wget \
          xz-utils \
          zip

      - name: Install CMake
        run: |
          wget -q https://github.com/Kitware/CMake/releases/download/v4.1.2/cmake-4.1.2-linux-x86_64.tar.gz && \
          mkdir -p /opt/cmake-4.1.2 && \
          sudo tar -xzf cmake-4.1.2-linux-x86_64.tar.gz -C /opt/cmake-4.1.2 --strip-components=1 && \
          sudo ln -sf /opt/cmake-4.1.2/bin/cmake /usr/local/bin/cmake

      - name: Install Tool
        run: ./tool/run.sh
        working-directory: main

      - name: Generate Image
        run: ./misc/gen-circle.sh
        working-directory: main

      - name: Build WASM
        run: ./wasm.sh
        working-directory: main

      - name: Save Github Pages
        uses: devops-infra/action-commit-push@v1.0.3
        with:
          amend: true
          force: true
          path: main/gh-pages
